spring.application.name=Innovatech
server.port=18080

spring.datasource.url=jdbc:mysql://localhost:3306/db_employees?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true